const courseCard = [
    {
        // image: "/images/full-stack-devlopment-min.png",
        image: "https://midu.dev//images/og/bootcamp-full-stack-gratis-2021.jpg",
        title: "Devlopment",
        alt: "img",
        name: "Introduction Web Developer |",
        hour: "1",
        minute: "15",
        rate: "4.8",
    },
    {
        image: "/images/1_3nssFciPfRIZaJfnnFipKA.png",
        title: "Devlopment",
        alt: "img",
        name: "Introduction Web Developer |",
        hour: "2",
        minute: "15",
        rate: "4.8",
    },
    {
        image: "/images/1_OaQpmkPzetUvWAB5sO9ZVg.png",
        title: "Devlopment",
        alt: "img",
        name: "Introduction Web Developer |",
        hour: "3",
        minute: "15",
        rate: "4.8",
    },
    {
        image: "https://i0.wp.com/hocjavascript.net/wp-content/uploads/2022/02/Lam-the-nao-de-hoc-Full-Stack-Development.jpg",
        title: "Devlopment",
        alt: "img",
        name: "Introduction Web Developer |",
        hour: "3",
        minute: "15",
        rate: "4.8",
    },
    {
        image: "https://midu.dev//images/og/bootcamp-full-stack-gratis-2021.jpg",
        title: "Devlopment",
        alt: "img",
        name: "Introduction Web Developer |",
        hour: "3",
        minute: "15",
        rate: "4.8",
    },
    {
        image: "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/170175384/original/4f4353fd791ef7e0ec8ac964ca82ba2573eed56c/be-your-full-stack-developer-monthly-basis.jpg",
        title: "Devlopment",
        alt: "img",
        name: "Introduction Web Developer |",
        hour: "3",
        minute: "15",
        rate: "4.8",
    },
];

export { courseCard };
